#!/usr/bin/env python3
"""Acquire a clipped USGS CoNED San Francisco 2 m topobathy raster via WCS."""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlencode


ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "paleo-coastlines" / "raw" / "usgs-coned-sf-2m"
PUBLIC_DIR = ROOT / "public" / "data" / "paleo-coastlines"
OUT_JSON = PUBLIC_DIR / "usgs_coned_sf_2m_manifest.json"
OUT_MD = ROOT / "docs" / "usgs-coned-sf-2m.md"

WCS_BASE_URL = "https://dmsdata.cr.usgs.gov/geoserver/wcs"
VIEWER_URL = "https://topotools.cr.usgs.gov/topobathy_viewer/"
SOURCE_URL = "https://www.usgs.gov/special-topics/coastal-national-elevation-database-applications-project/science/topobathymetric-0"
LAYER_NAME = "topo:San_Francisco_TopoBathy_Elevation_2m"
TARGET_NAME = "coned_sf_2m_best_available_8192.tif"

# Match the app's fused Golden Gate-to-Farallones focus rectangle. The source
# itself only covers the San Francisco CoNED region, so empty offshore areas are
# expected outside the WCS layer bounds.
DEFAULT_BOUNDS = {
    "west": -123.55,
    "south": 37.35,
    "east": -122.15,
    "north": 38.15,
}


def web_mercator(lon: float, lat: float) -> tuple[float, float]:
    radius = 6_378_137.0
    x = radius * math.radians(lon)
    y = radius * math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))
    return x, y


def projected_bbox(bounds: dict[str, float]) -> tuple[float, float, float, float]:
    west, south = web_mercator(bounds["west"], bounds["south"])
    east, north = web_mercator(bounds["east"], bounds["north"])
    return west, south, east, north


def target_height(bounds: dict[str, float], width: int) -> int:
    west, south, east, north = projected_bbox(bounds)
    ratio = abs(north - south) / abs(east - west)
    return max(1, round(width * ratio))


def wcs_url(bounds: dict[str, float], width: int, height: int) -> str:
    west, south, east, north = projected_bbox(bounds)
    params = {
        "SERVICE": "WCS",
        "VERSION": "1.0.0",
        "REQUEST": "GetCoverage",
        "COVERAGE": LAYER_NAME,
        "CRS": "EPSG:3857",
        "BBOX": f"{west},{south},{east},{north}",
        "WIDTH": str(width),
        "HEIGHT": str(height),
        "FORMAT": "GeoTIFF",
    }
    return f"{WCS_BASE_URL}?{urlencode(params)}"


def human_size(size: int | float | None) -> str:
    if size is None:
        return "unknown"
    value = float(size)
    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            return f"{value:.1f} {unit}" if unit != "B" else f"{value:.0f} B"
        value /= 1024
    return f"{value:.1f} GB"


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def write_markdown(payload: dict[str, Any]) -> None:
    local_path = payload["localPath"]
    lines = [
        "# USGS CoNED San Francisco 2 m Topobathy",
        "",
        "This file is generated by `python3 scripts/acquire_usgs_coned_sf_2m.py`.",
        "",
        "Plain-English purpose: this is a unified land-plus-seafloor elevation surface for the San Francisco CoNED region. It helps the app keep the Bay, shoreline, and nearshore terrain tied together before smaller survey patches are layered on top.",
        "",
        "## Source",
        "",
        f"- CoNED project page: {SOURCE_URL}",
        f"- CoNED viewer: {VIEWER_URL}",
        f"- WCS layer: `{LAYER_NAME}`",
        f"- WCS endpoint: {WCS_BASE_URL}",
        "",
        "## Local Output",
        "",
        f"- GeoTIFF: `{local_path}`",
        f"- Size: {payload['localSizeHuman']}",
        f"- Request width/height: {payload['request']['width']} x {payload['request']['height']}",
        f"- Bounds: {payload['bounds']['west']}, {payload['bounds']['south']} to {payload['bounds']['east']}, {payload['bounds']['north']}",
        "",
        "## Caveats",
        "",
        "- This is a WCS clip, not the full enormous native CoNED raster.",
        "- The native source is 2 m, but this app-facing clip is downsampled to keep the local project usable.",
        "- Use it as a strong local continuity surface, then let higher-resolution BAG, OCM, CSMP, DS684, LiDAR, and source-survey patches win where they overlap.",
        "- CoNED still needs datum comparison before exact sea-level claims.",
        "",
    ]
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines))


def validate_download(path: Path) -> None:
    if path.stat().st_size < 1024 * 1024:
        raise RuntimeError(f"CoNED WCS download is too small: {human_size(path.stat().st_size)}")
    with path.open("rb") as handle:
        prefix = handle.read(64).lower()
    if prefix.startswith(b"<!doctype html") or prefix.startswith(b"<html") or prefix.startswith(b"<?xml"):
        raise RuntimeError("CoNED WCS download returned text instead of GeoTIFF data")


def download(url: str, target: Path, force: bool) -> None:
    if target.exists() and not force:
        print(f"Using existing file: {target.relative_to(ROOT)}")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    part_path = target.with_name(f"{target.name}.part")
    part_path.unlink(missing_ok=True)
    if shutil.which("curl") is None:
        raise RuntimeError("curl is required for this WCS download")
    print(f"Downloading {url}")
    print(f"to {target.relative_to(ROOT)}")
    subprocess.run(
        [
            "curl",
            "--location",
            "--fail",
            "--retry",
            "3",
            "--retry-delay",
            "5",
            "--retry-all-errors",
            "--connect-timeout",
            "30",
            "--speed-limit",
            "1",
            "--speed-time",
            "300",
            "--max-time",
            "7200",
            "--output",
            str(part_path),
            url,
        ],
        check=True,
    )
    validate_download(part_path)
    part_path.replace(target)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--download", action="store_true", help="Download the WCS GeoTIFF clip.")
    parser.add_argument("--force", action="store_true", help="Redownload even if the local file exists.")
    parser.add_argument("--width", type=int, default=8192, help="Requested WCS output width in pixels.")
    args = parser.parse_args()

    bounds = DEFAULT_BOUNDS.copy()
    height = target_height(bounds, args.width)
    target = RAW_DIR / TARGET_NAME
    url = wcs_url(bounds, args.width, height)

    if args.download:
        download(url, target, args.force)

    payload = {
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source": {
            "label": "USGS CoNED San Francisco 2 m topobathymetric DEM",
            "sourceUrl": SOURCE_URL,
            "viewerUrl": VIEWER_URL,
            "wcsBaseUrl": WCS_BASE_URL,
            "layerName": LAYER_NAME,
        },
        "bounds": bounds,
        "projectedBoundsEpsg3857": projected_bbox(bounds),
        "request": {
            "width": args.width,
            "height": height,
            "url": url,
        },
        "localPath": str(target.relative_to(ROOT)),
        "localPresent": target.exists(),
        "localSizeBytes": target.stat().st_size if target.exists() else 0,
        "localSizeHuman": human_size(target.stat().st_size) if target.exists() else "not downloaded",
    }
    write_json(OUT_JSON, payload)
    write_markdown(payload)
    print(f"Wrote {OUT_JSON.relative_to(ROOT)}")
    print(f"Wrote {OUT_MD.relative_to(ROOT)}")
    print(json.dumps({
        "downloaded": bool(args.download),
        "localPresent": payload["localPresent"],
        "localSize": payload["localSizeHuman"],
        "width": args.width,
        "height": height,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
