#!/usr/bin/env python3
"""Acquire a clipped USGS CoNED San Francisco 2 m topobathy raster via WCS."""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlencode


ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "paleo-coastlines" / "raw" / "usgs-coned-sf-2m"
PUBLIC_DIR = ROOT / "public" / "data" / "paleo-coastlines"
OUT_JSON = PUBLIC_DIR / "usgs_coned_sf_2m_manifest.json"
OUT_MD = ROOT / "docs" / "usgs-coned-sf-2m.md"

WCS_BASE_URL = "https://dmsdata.cr.usgs.gov/geoserver/wcs"
VIEWER_URL = "https://topotools.cr.usgs.gov/topobathy_viewer/"
SOURCE_URL = "https://www.usgs.gov/special-topics/coastal-national-elevation-database-applications-project/science/topobathymetric-0"
LAYER_NAME = "topo:San_Francisco_TopoBathy_Elevation_2m"
CONED_CLIPS: dict[str, dict[str, Any]] = {
    "best_available": {
        "targetName": "coned_sf_2m_best_available_8192.tif",
        "width": 8192,
        "bounds": {"west": -123.55, "south": 37.35, "east": -122.15, "north": 38.15},
        "description": "Broad Bay-to-Farallones continuity clip used as the first CoNED app source.",
    },
    "gate_shelf": {
        "targetName": "coned_sf_2m_gate_shelf_8192.tif",
        "width": 8192,
        "bounds": {"west": -122.92, "south": 37.55, "east": -122.32, "north": 37.95},
        "description": "Higher-pixel-density clip around the Golden Gate, San Francisco Bar, Ocean Beach, and the inner shelf.",
    },
    "farallon_shelf": {
        "targetName": "coned_sf_2m_farallon_shelf_8192.tif",
        "width": 8192,
        "bounds": {"west": -123.34, "south": 37.42, "east": -122.70, "north": 37.95},
        "description": "Higher-pixel-density clip across the Farallon Islands approach and outer shelf.",
    },
    "south_bay_edge": {
        "targetName": "coned_sf_2m_south_bay_edge_8192.tif",
        "width": 8192,
        "bounds": {"west": -122.58, "south": 37.35, "east": -122.14, "north": 37.78},
        "description": "Higher-pixel-density clip for the south and lower-central Bay edge inside the public CoNED layer bounds.",
    },
}


def web_mercator(lon: float, lat: float) -> tuple[float, float]:
    radius = 6_378_137.0
    x = radius * math.radians(lon)
    y = radius * math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))
    return x, y


def projected_bbox(bounds: dict[str, float]) -> tuple[float, float, float, float]:
    west, south = web_mercator(bounds["west"], bounds["south"])
    east, north = web_mercator(bounds["east"], bounds["north"])
    return west, south, east, north


def target_height(bounds: dict[str, float], width: int) -> int:
    west, south, east, north = projected_bbox(bounds)
    ratio = abs(north - south) / abs(east - west)
    return max(1, round(width * ratio))


def wcs_url(bounds: dict[str, float], width: int, height: int) -> str:
    west, south, east, north = projected_bbox(bounds)
    params = {
        "SERVICE": "WCS",
        "VERSION": "1.0.0",
        "REQUEST": "GetCoverage",
        "COVERAGE": LAYER_NAME,
        "CRS": "EPSG:3857",
        "BBOX": f"{west},{south},{east},{north}",
        "WIDTH": str(width),
        "HEIGHT": str(height),
        "FORMAT": "GeoTIFF",
    }
    return f"{WCS_BASE_URL}?{urlencode(params)}"


def human_size(size: int | float | None) -> str:
    if size is None:
        return "unknown"
    value = float(size)
    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            return f"{value:.1f} {unit}" if unit != "B" else f"{value:.0f} B"
        value /= 1024
    return f"{value:.1f} GB"


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def write_markdown(payload: dict[str, Any]) -> None:
    clips = payload["clips"]
    lines = [
        "# USGS CoNED San Francisco 2 m Topobathy",
        "",
        "This file is generated by `python3 scripts/acquire_usgs_coned_sf_2m.py`.",
        "",
        "Plain-English purpose: this is a unified land-plus-seafloor elevation surface for the San Francisco CoNED region. It helps the app keep the Bay, shoreline, and nearshore terrain tied together before smaller survey patches are layered on top.",
        "",
        "## Source",
        "",
        f"- CoNED project page: {SOURCE_URL}",
        f"- CoNED viewer: {VIEWER_URL}",
        f"- WCS layer: `{LAYER_NAME}`",
        f"- WCS endpoint: {WCS_BASE_URL}",
        "",
        "## Local Output",
        "",
        "| Clip | GeoTIFF | Size | Request | Bounds |",
        "|---|---|---:|---:|---|",
        *[
            f"| {clip['id']} | `{clip['localPath']}` | {clip['localSizeHuman']} | {clip['request']['width']} x {clip['request']['height']} | {clip['bounds']['west']}, {clip['bounds']['south']} to {clip['bounds']['east']}, {clip['bounds']['north']} |"
            for clip in clips
        ],
        "",
        "## Caveats",
        "",
        "- These are WCS clips, not the full enormous native CoNED raster.",
        "- The native source is 2 m. Larger broad clips are still downsampled; smaller focus clips keep more pixels per mile.",
        "- Use it as a strong local continuity surface, then let higher-resolution BAG, OCM, CSMP, DS684, LiDAR, and source-survey patches win where they overlap.",
        "- CoNED still needs datum comparison before exact sea-level claims.",
        "",
    ]
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines))


def validate_download(path: Path) -> None:
    if path.stat().st_size < 1024 * 1024:
        raise RuntimeError(f"CoNED WCS download is too small: {human_size(path.stat().st_size)}")
    with path.open("rb") as handle:
        prefix = handle.read(64).lower()
    if prefix.startswith(b"<!doctype html") or prefix.startswith(b"<html") or prefix.startswith(b"<?xml"):
        raise RuntimeError("CoNED WCS download returned text instead of GeoTIFF data")


def download(url: str, target: Path, force: bool) -> None:
    if target.exists() and not force:
        print(f"Using existing file: {target.relative_to(ROOT)}")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    part_path = target.with_name(f"{target.name}.part")
    part_path.unlink(missing_ok=True)
    if shutil.which("curl") is None:
        raise RuntimeError("curl is required for this WCS download")
    print(f"Downloading {url}")
    print(f"to {target.relative_to(ROOT)}")
    subprocess.run(
        [
            "curl",
            "--location",
            "--fail",
            "--retry",
            "3",
            "--retry-delay",
            "5",
            "--retry-all-errors",
            "--connect-timeout",
            "30",
            "--speed-limit",
            "1",
            "--speed-time",
            "300",
            "--max-time",
            "7200",
            "--output",
            str(part_path),
            url,
        ],
        check=True,
    )
    validate_download(part_path)
    part_path.replace(target)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--download", action="store_true", help="Download the WCS GeoTIFF clip.")
    parser.add_argument("--force", action="store_true", help="Redownload even if the local file exists.")
    parser.add_argument(
        "--clip",
        choices=[*CONED_CLIPS.keys(), "all"],
        default="best_available",
        help="Named CoNED clip to process. Use all for every configured clip.",
    )
    parser.add_argument("--width", type=int, default=None, help="Override requested WCS output width in pixels.")
    args = parser.parse_args()

    clip_ids = list(CONED_CLIPS.keys()) if args.clip == "all" else [args.clip]
    clips: list[dict[str, Any]] = []

    for clip_id in clip_ids:
        clip = CONED_CLIPS[clip_id]
        bounds = dict(clip["bounds"])
        width = int(args.width or clip["width"])
        height = target_height(bounds, width)
        target = RAW_DIR / str(clip["targetName"])
        url = wcs_url(bounds, width, height)

        if args.download:
            download(url, target, args.force)

        local_size = target.stat().st_size if target.exists() else 0
        clips.append({
            "id": clip_id,
            "description": clip["description"],
            "bounds": bounds,
            "projectedBoundsEpsg3857": projected_bbox(bounds),
            "request": {
                "width": width,
                "height": height,
                "url": url,
            },
            "localPath": str(target.relative_to(ROOT)),
            "localPresent": target.exists(),
            "localSizeBytes": local_size,
            "localSizeHuman": human_size(local_size) if target.exists() else "not downloaded",
        })

    payload = {
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source": {
            "label": "USGS CoNED San Francisco 2 m topobathymetric DEM",
            "sourceUrl": SOURCE_URL,
            "viewerUrl": VIEWER_URL,
            "wcsBaseUrl": WCS_BASE_URL,
            "layerName": LAYER_NAME,
        },
        "selection": args.clip,
        "clips": clips,
    }
    write_json(OUT_JSON, payload)
    write_markdown(payload)
    print(f"Wrote {OUT_JSON.relative_to(ROOT)}")
    print(f"Wrote {OUT_MD.relative_to(ROOT)}")
    print(json.dumps({
        "downloaded": bool(args.download),
        "selection": args.clip,
        "clips": [
            {
                "id": clip["id"],
                "localPresent": clip["localPresent"],
                "localSize": clip["localSizeHuman"],
                "width": clip["request"]["width"],
                "height": clip["request"]["height"],
            }
            for clip in clips
        ],
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
