#!/usr/bin/env python3
"""Bounds-only processing for B00012 raw multibeam files."""

from __future__ import annotations

import json
import subprocess
import sys
import urllib.parse
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from urllib.request import urlopen


ROOT = Path(__file__).resolve().parents[1]
B00012_PAGE = "https://www.ngdc.noaa.gov/ships/davidson/B00012_mb.html"
DEFAULT_WORK_DIR = ROOT / "data" / "paleo-coastlines" / "raw-sonar-probe"
OUT_JSON = ROOT / "public" / "data" / "paleo-coastlines" / "b00012_bounds_batch_summary.json"
OUT_MD = ROOT / "docs" / "b00012-bounds-batch-summary.md"
QG_05_12 = [-123.375, 38.0628604, -123.3603027, 38.0772128]


class LinkParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.links: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag != "a":
            return
        href = dict(attrs).get("href")
        if href:
            self.links.append(urllib.parse.urljoin(B00012_PAGE, href))


def raw_links() -> list[str]:
    parser = LinkParser()
    with urlopen(B00012_PAGE, timeout=30) as response:
        parser.feed(response.read().decode("utf-8", errors="replace"))
    return [link for link in parser.links if link.endswith(".mb15")]


def sample_id_for_url(url: str) -> str:
    name = Path(urllib.parse.urlparse(url).path).name
    return f"b00012-{name.removesuffix('.sbo.mb15')}"


def report_path(work_dir: Path, sample_id: str, url: str) -> Path:
    name = Path(urllib.parse.urlparse(url).path).name
    return work_dir / sample_id / f"{sample_id}-{name}.sample-report.json"


def bounds_from_report(path: Path) -> list[float] | None:
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    stats = data.get("stats") or {}
    required = ["minLon", "minLat", "maxLon", "maxLat"]
    if any(key not in stats for key in required):
        return None
    return [float(stats["minLon"]), float(stats["minLat"]), float(stats["maxLon"]), float(stats["maxLat"])]


def bounds_overlap(a: list[float] | None, b: list[float]) -> bool:
    if not a:
        return False
    aw, asouth, ae, anorth = a
    bw, bsouth, be, bnorth = b
    return not (ae < bw or be < aw or anorth < bsouth or bnorth < asouth)


def run_processor(url: str, sample_id: str, work_dir: Path) -> None:
    command = [
        sys.executable,
        str(ROOT / "scripts" / "process_raw_multibeam_sample.py"),
        "--survey-id",
        sample_id,
        "--url",
        url,
        "--format",
        "15",
        "--work-dir",
        str(work_dir),
        "--skip-grid",
    ]
    subprocess.run(command, check=True)


def build_summary(work_dir: Path, limit: int | None = None) -> dict:
    entries = []
    for url in raw_links()[:limit]:
        sample_id = sample_id_for_url(url)
        path = report_path(work_dir, sample_id, url)
        if not path.exists():
            run_processor(url, sample_id, work_dir)
        bounds = bounds_from_report(path)
        data = json.loads(path.read_text())
        stats = data.get("stats") or {}
        entries.append({
            "sampleId": sample_id,
            "fileName": Path(urllib.parse.urlparse(url).path).name,
            "url": url,
            "reportPath": str(path.relative_to(ROOT)) if path.is_relative_to(ROOT) else str(path),
            "bounds": bounds,
            "overlapsQG0512": bounds_overlap(bounds, QG_05_12),
            "validPointCount": stats.get("unthinnedValidPointCount") or stats.get("validPointCount"),
            "minZ": stats.get("minZ"),
            "maxZ": stats.get("maxZ"),
        })
    return {
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "plainEnglishPurpose": "Process B00012 raw files in bounds-only mode and identify which ones overlap qg-05-12.",
        "cellId": "qg-05-12",
        "cellBounds": QG_05_12,
        "files": entries,
        "overlapCount": sum(1 for entry in entries if entry["overlapsQG0512"]),
    }


def write_markdown(summary: dict) -> None:
    lines = [
        "# B00012 Bounds Batch Summary",
        "",
        "This file is generated by `python3 scripts/process_b00012_bounds_batch.py`.",
        "",
        "Plain English: process each B00012 raw file just enough to learn its point bounds, then mark which files touch weak cell `qg-05-12`.",
        "",
        f"Files overlapping `qg-05-12`: **{summary['overlapCount']}** of {len(summary['files'])}.",
        "",
        "| File | Touches qg-05-12? | Bounds | Points | Depth range |",
        "|---|---:|---|---:|---|",
    ]
    for entry in summary["files"]:
        bounds = entry.get("bounds")
        bounds_text = (
            f"`{bounds[0]:.6f}, {bounds[1]:.6f}, {bounds[2]:.6f}, {bounds[3]:.6f}`"
            if bounds else "-"
        )
        points = entry.get("validPointCount") or 0
        depth = (
            f"`{entry['minZ']}` to `{entry['maxZ']}`"
            if entry.get("minZ") is not None and entry.get("maxZ") is not None else "-"
        )
        lines.append(
            f"| `{entry['fileName']}` | {'yes' if entry['overlapsQG0512'] else 'no'} | "
            f"{bounds_text} | {points:,} | {depth} |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n")


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Bounds-only process B00012 raw multibeam files.")
    parser.add_argument("--work-dir", type=Path, default=DEFAULT_WORK_DIR)
    parser.add_argument("--limit", type=int)
    args = parser.parse_args()

    summary = build_summary(args.work_dir, args.limit)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(summary, indent=2) + "\n")
    write_markdown(summary)
    print(json.dumps({
        "files": len(summary["files"]),
        "overlapCount": summary["overlapCount"],
        "overlappingFiles": [entry["fileName"] for entry in summary["files"] if entry["overlapsQG0512"]],
    }, indent=2))


if __name__ == "__main__":
    main()
